name: Build test RC

on:
    pull_request_review:
      types:
        - submitted
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build_test_rc:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
                cache: "pip"

            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r tasks/libs/requirements-github.txt
                  
            - name: Build RC
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git fetch
                inv -e release.build-rc --test-build