name: Create RC PR

on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    create_rc_pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
                cache: "pip"

            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r tasks/libs/requirements-github.txt

            - name: Determine the release active branch
              run: |
                echo "RELEASE_BRANCH=$(inv -e release.get-active-release-branch)" >> $GITHUB_ENV
            
            - name: Checkout release branch
              uses: actions/checkout@v4
              with:
                ref: ${{ env.RELEASE_BRANCH }}
                fetch-depth: 0

            - name: Check for changes since last RC
              run: |
                rc_pattern=$(echo "${{ env.RELEASE_BRANCH }}" | cut -c 1-5)
                last_rc_commit=$(git rev-list --all -i --grep="$rc_pattern" --max-count=1)
                git rev-list --count HEAD ^"$last_rc_commit"
                if [ $? -eq 0 ]; then
                  echo "No changes since last RC. Quitting workflow."
                  exit 0
                fi
              
            - name: Create RC PR
              if: ${{ success() }}
              run: |
                git config user.name "GitHub Actions"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git fetch
                inv -e release.create-rc
